### ISSUE TITLE
Implement validation view

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/nirdizati-training-ui#11]
This view would provide user information about completed runs.

Also this page should provide ability for user to export trained models into runtime component.

Will create separate issue for model importing since I feel this will quite a task, since we need suitable format for runtime component to be able to use the model.

Prototype for this page can be found [here](https://app.moqups.com/zukkari/RkWHWPmhrb/edit/page/a5b34ba85)

**Comment by Zukkari** [comment]
Validation view should be openable from job tracking grid. This would make the grid to include data from the job it was redirected from.

**Comment by verenich** [comment]
You will need to collect all the training configurations then and show them e.g. in a table with clickable rows that will enable viz of a specific configuration

**Comment by Zukkari** [comment]
Well this would mean that user would also see other users results. What I thought is I could load the jobs based on the cookie they were run from since jobs would still be in memory, or I could add an additional parameter 'owner' to the training parameters file so I could read the jobs in even after the restart of the program.

**Comment by verenich** [comment]
I like the second option
