### ISSUE TITLE
Look into user file conversion

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/nirdizati-training-ui#118]
Currently we only support ```.CSV``` logs with ```;``` as a delimiter. That is pretty bad because CSV is a comma separated values, not semicolon.

- UI should parse user logs and replace ```,``` with ```;``` since user has no ability to download log anyway.
- Should also look into ```.XES``` log conversion to CSV format.

**Comment by verenich** [comment]
The issue with csv can be **partially** resolved on my side if I set a separator via regex, i.e. `sep=",|;" `

Note, this will still create a problem if the columns are separeted with a semicolon AND a colon is used somewhere inside a column (i.e. a comma as a thousands separator for values over 1,000"

**Comment by Zukkari** [comment]
I think the way to resolve this issue is that when parsing user file we check what character appears more often in the first line of the log file. Doubt that the separator will be present less times than another sign.

**Comment by verenich** [comment]
not sure what exactly you mean by "the first line of the log file" - the header or the first actual line of data. But either way, it is not going to be robust:
## helpdesk.csv:
```
header_string='case_id;Resource;customer;org.resource;product;responsible_section;seriousness;service_level;service_type;support_section;workgroup;time;remtime;elapsed;activity_name;open_cases'
dict((letter,header_string.count(letter)) for letter in set(header_string))

```
gives us
```
{'.': 1,
 ';': 15,
 'R': 1,
 '_': 7,
 'a': 5,
 'b': 1,
 'c': 11,
 'd': 3,
 'e': 27,
 'g': 2,
 'i': 11,
 'k': 1,
 'l': 4,
 'm': 5,
 'n': 6,
 'o': 13,
 'p': 8,
 'r': 14,
 's': 18,
 't': 10,
 'u': 7,
 'v': 4,
 'w': 1,
 'y': 2}
```
; is not the most common character.

## BPI2012W:
```
first_line='173688;A_SUBMITTED;112;20000;0.0;2011-09-30 23:38:44;1072725.0;1'
dict((letter,first_line.count(letter)) for letter in set(first_line))
```
gives us:
```
{' ': 1,
 '-': 2,
 '.': 2,
 '0': 11,
 '1': 7,
 '2': 6,
 '3': 4,
 '4': 2,
 '5': 1,
 '6': 1,
 '7': 3,
 '8': 3,
 '9': 1,
 ':': 2,
 ';': 7,
 'A': 1,
 'B': 1,
 'D': 1,
 'E': 1,
 'I': 1,
 'M': 1,
 'S': 1,
 'T': 2,
 'U': 1,
 '_': 1}

```
0 is more common than ;

**Comment by Zukkari** [comment]
Yes, but what I meant is we check the frequency for common delimiter chars e.g. ```; or ,```. Or another option is to let user input delim char.

**Comment by Zukkari** [comment]
This has been fixed. 
5acef32 on script side and 45e16b34c9f82ec20e20dcb468b94317a4aa72e8 on ui side
