### ISSUE TITLE
Add model performance column in the validation table

### ISSUE THREAD

**Issue by verenich** [Zukkari/nirdizati-training-ui#146]
Use Case: a user has trained multiple models with different config, currently, there is no way to tell which one is better **on average** except opening one of them and selecting "COMPARE WITH OTHER RELEVANT MODELS" one by one

Solution: add a column with aggregated (average) performance to the validation column. For regression, it could be MAE, for classification - Logloss, but the column can be just called "accuracy", to keep it generic.

Since all the other information for this table is pulled from the training config json, I can write this extra number to be displayed there, e.g.
```
{
    "remtime":{
        "state": {
            "laststate":{
                "rf":{
                    "max_features":0.5,"n_estimators":300
                }
            }
        }
    },
    "ui_data":{
        "start_time":"2018-05-04T05:19:31.542Z",
        "log_file":"/home/ubuntu/git/nirdizati-training-ui/PredictiveMethods/logdata/bpi12.csv",
        "job_owner":"d074156c0eb22ac57d5237b0a7a5d420"
    },
    "evaluation":{
        "mae":0.465
    }
}
```

A cleaner way is to insert it into `results/validation/*.csv`: 
```
label_col,bucket_method,feat_encoding,cls,nr_events,metric,score
remtime,state,laststate,rf,1,mae,5.326418043
remtime,state,laststate,rf,2,mae,6.7116711112
remtime,state,laststate,rf,3,rmse,4.3599907364
...
remtime,state,laststate,rf,**avg**,rmse,5.3599907364
```

**Comment by Zukkari** [comment]
I find first option to be more suitable because if you include this into the results file then I will have to redo the results parsing to exclude last line and handle it independently etc.

With the first option though I suggest that the format could be:
```
    "evaluation" : {
        "metric": "mae",
        "value": 0.465
    }
```
This way I will be able to handle the metric in a more generic way and will not actually need to know what the metric is.

**Comment by verenich** [comment]
@Zukkari done, using the first option
