### ISSUE TITLE
Use hyperoptimized parameters if available

### ISSUE THREAD

**Issue by verenich** [Zukkari/nirdizati-training-ui#25]
When a user selects a training config (or it is pre-selected), we need to check if we have the optimal learner's hyperparameters for that config in `optimal_params/{log_name_wo_extension}.json`. If so, these parameters should be displayed in the box and passed to `training_params/{log_name_wo_extension}.json` . Otherwise, this file should be created based on the default parameters

**Comment by Zukkari** [comment]
Implemented for basic mode. @verenich mentioned that for advanced mode this was not needed.
