### ISSUE TITLE
Implement upload page

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/nirdizati-training-ui#4]
This page will give user ability to upload his logs.
How this page should can be seen [here](https://app.moqups.com/zukkari/RkWHWPmhrb/edit/page/ad64222d5)

On this page user will be able to:

- Choose a log for uploading
- Upload his log in .XES format
- Given instructions how to convert his log to .XES format.

After successful upload user will be prompted to continue to overview log in appropriate view.

**Comment by Zukkari** [comment]
Currently user does not receive notification when uploading is complete. 

I am planning to add a progress bar which indicates progress of an upload process.

After the process completes, what should be the desired outcome? Should user be redirected to log overview page? Or should user receive a notification with a button that allows his to be redirected to the log overview page when he clicks it? @verenich

**Comment by verenich** [comment]
I think a user should be redirected to a training page, no need for log overview unless he explicitly goes there
