### ISSUE TITLE
Clustering does not generate grid when is selected alone.

### ISSUE THREAD

**Issue by Zukkari** [Zukkari/nirdizati-training-ui#59]
When hyperparameter that is not a learner is selected and this parameter has properties then grid is not generated for this parameter. How should this be handled? Grids are only generated for learners and then other parameters that have properties such as clustering are added as additional row for those grids.

If nothing is selected and clustering is selected, how should this be handled? Should we generate grids for all learners then with e.g. 1 row if clustering is checked?

**Comment by verenich** [comment]
If clustering is selected, but no other learner is selected, you do not need to offer `Number of clusters` until one of the learners will be selected, and number of clusters should be an extra parameter in the grid (e.g topmost)
